/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

/**
 *
 * @author rafae
 */
public class PNombresDatos extends javax.swing.JPanel {

    /**
     * Creates new form PNombresDatos
     */
    public PNombresDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRedondeado11 = new utilerias.PanelRedondeado();
        jLabel5 = new javax.swing.JLabel();
        panelRedondeado13 = new utilerias.PanelRedondeado();
        jLabel4 = new javax.swing.JLabel();
        panelRedondeado15 = new utilerias.PanelRedondeado();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        panelRedondeado16 = new utilerias.PanelRedondeado();
        jLabel7 = new javax.swing.JLabel();
        panelRedondeado17 = new utilerias.PanelRedondeado();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRedondeado11.setBackground(new java.awt.Color(0, 51, 153));
        panelRedondeado11.setRoundBottomLeft(16);
        panelRedondeado11.setRoundBottomRight(16);
        panelRedondeado11.setRoundTopLeft(16);
        panelRedondeado11.setRoundTopRight(16);

        jLabel5.setBackground(new java.awt.Color(245, 245, 245));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellidos");

        javax.swing.GroupLayout panelRedondeado11Layout = new javax.swing.GroupLayout(panelRedondeado11);
        panelRedondeado11.setLayout(panelRedondeado11Layout);
        panelRedondeado11Layout.setHorizontalGroup(
            panelRedondeado11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        panelRedondeado11Layout.setVerticalGroup(
            panelRedondeado11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelRedondeado11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 260, 40));

        panelRedondeado13.setBackground(new java.awt.Color(0, 51, 153));
        panelRedondeado13.setForeground(new java.awt.Color(0, 0, 204));
        panelRedondeado13.setRoundBottomLeft(16);
        panelRedondeado13.setRoundBottomRight(16);
        panelRedondeado13.setRoundTopLeft(16);
        panelRedondeado13.setRoundTopRight(16);

        jLabel4.setBackground(new java.awt.Color(245, 245, 245));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");

        javax.swing.GroupLayout panelRedondeado13Layout = new javax.swing.GroupLayout(panelRedondeado13);
        panelRedondeado13.setLayout(panelRedondeado13Layout);
        panelRedondeado13Layout.setHorizontalGroup(
            panelRedondeado13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(204, Short.MAX_VALUE))
        );
        panelRedondeado13Layout.setVerticalGroup(
            panelRedondeado13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelRedondeado13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 260, 40));

        panelRedondeado15.setBackground(new java.awt.Color(0, 51, 153));
        panelRedondeado15.setRoundBottomLeft(16);
        panelRedondeado15.setRoundBottomRight(16);
        panelRedondeado15.setRoundTopLeft(16);
        panelRedondeado15.setRoundTopRight(16);

        jLabel8.setBackground(new java.awt.Color(245, 245, 245));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fecha de Nacimiento");

        javax.swing.GroupLayout panelRedondeado15Layout = new javax.swing.GroupLayout(panelRedondeado15);
        panelRedondeado15.setLayout(panelRedondeado15Layout);
        panelRedondeado15Layout.setHorizontalGroup(
            panelRedondeado15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRedondeado15Layout.setVerticalGroup(
            panelRedondeado15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRedondeado15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelRedondeado15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 260, 40));

        panelRedondeado16.setBackground(new java.awt.Color(0, 51, 153));
        panelRedondeado16.setRoundBottomLeft(16);
        panelRedondeado16.setRoundBottomRight(16);
        panelRedondeado16.setRoundTopLeft(16);
        panelRedondeado16.setRoundTopRight(16);

        jLabel7.setBackground(new java.awt.Color(245, 245, 245));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Direccion");

        javax.swing.GroupLayout panelRedondeado16Layout = new javax.swing.GroupLayout(panelRedondeado16);
        panelRedondeado16.setLayout(panelRedondeado16Layout);
        panelRedondeado16Layout.setHorizontalGroup(
            panelRedondeado16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        panelRedondeado16Layout.setVerticalGroup(
            panelRedondeado16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelRedondeado16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 260, 40));

        panelRedondeado17.setBackground(new java.awt.Color(0, 51, 153));
        panelRedondeado17.setRoundBottomLeft(16);
        panelRedondeado17.setRoundBottomRight(16);
        panelRedondeado17.setRoundTopLeft(16);
        panelRedondeado17.setRoundTopRight(16);

        jLabel9.setBackground(new java.awt.Color(245, 245, 245));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Correo");

        javax.swing.GroupLayout panelRedondeado17Layout = new javax.swing.GroupLayout(panelRedondeado17);
        panelRedondeado17.setLayout(panelRedondeado17Layout);
        panelRedondeado17Layout.setHorizontalGroup(
            panelRedondeado17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRedondeado17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(212, Short.MAX_VALUE))
        );
        panelRedondeado17Layout.setVerticalGroup(
            panelRedondeado17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRedondeado17Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        add(panelRedondeado17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private utilerias.PanelRedondeado panelRedondeado11;
    private utilerias.PanelRedondeado panelRedondeado13;
    private utilerias.PanelRedondeado panelRedondeado15;
    private utilerias.PanelRedondeado panelRedondeado16;
    private utilerias.PanelRedondeado panelRedondeado17;
    // End of variables declaration//GEN-END:variables
}
